# Generated by Django 3.2.7 on 2021-09-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
                ('skill', models.CharField(max_length=40)),
                ('dark', models.CharField(max_length=10)),
                ('pic_url', models.CharField(max_length=150)),
                ('follower', models.CharField(max_length=10)),
                ('following', models.CharField(max_length=10)),
                ('post', models.CharField(max_length=10)),
            ],
        ),
    ]
