# Generated by Django 3.2.7 on 2021-09-16 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('description', models.TextField()),
                ('skill', models.CharField(max_length=40)),
                ('pic_url', models.ImageField(default='avatar.jpg', upload_to='user_pics')),
                ('dark', models.BooleanField(default=False)),
                ('follower', models.PositiveIntegerField(default=0)),
                ('following', models.PositiveIntegerField(default=0)),
                ('post', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
