# Generated by Django 3.2.7 on 2021-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='pic_url',
            field=models.ImageField(default='user_pics/avatar.jpg', upload_to='user_pics'),
        ),
    ]
