# Generated by Django 3.2.7 on 2021-09-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0003_alter_detail_pic_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_signed_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
    ]
