# Generated by Django 3.2.7 on 2021-09-17 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0004_user_signed_up'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_details',
        ),
        migrations.DeleteModel(
            name='user_signed_up',
        ),
    ]
