# Generated by Django 3.2.7 on 2021-09-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0005_auto_20210918_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_verify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30)),
                ('otp', models.CharField(max_length=40)),
                ('time_now', models.CharField(max_length=40)),
                ('time_after', models.CharField(max_length=40)),
            ],
        ),
    ]
