# Generated by Django 3.2.9 on 2021-11-12 04:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20211112_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 12, 4, 44, 48, 654079, tzinfo=utc)),
        ),
    ]
