# Generated by Django 3.2.9 on 2021-11-19 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_alter_post_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='uploads/post/default.png', upload_to='uploads/post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 10, 41, 19, 3051, tzinfo=utc)),
        ),
    ]
